hazelcast:
  network:
    join:
      multicast:
        enabled: false
      kubernetes:
        enabled: true
        namespace: default
        service-name: hazelcast-service
  cluster-name: my-hazelcast-cluster
